### ISSUE TITLE
Uncaught Exception: NameError: name 'charm' is not defined

### ISSUE THREAD

**Issue by devksingh4** [omnivector-solutions/charm-slurmctld#9]
Deploying via Juju 2.8.1 on MaaS 2.7.6

Deploying to Ubuntu 20.04 LTS

When deploying using tarball as resource (renamed to fit the constraints), the following error occurs: 
```
unit-slurmctld-1: 02:06:08 ERROR unit.slurmctld/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 86, in <module>
    main(SlurmctldCharm)
  File "/var/lib/juju/agents/unit-slurmctld-1/charm/venv/ops/main.py", line 333, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 28, in __init__
    self.slurm_ops_manager = SlurmOpsManager(self, "slurmctld")
  File "/var/lib/juju/agents/unit-slurmctld-1/charm/venv/slurm_ops_manager/slurm_ops.py", line 35, in __init__
    self.slurm_resource = SlurmTarManager(component, self._resource_path)
  File "/var/lib/juju/agents/unit-slurmctld-1/charm/venv/slurm_ops_manager/slurm_tar_ops.py", line 13, in __init__
    super().__init__(charm, component)
NameError: name 'charm' is not defined
```

**Comment by devksingh4** [comment]
Same error for slurmdbd and slurmd

**Comment by jamesbeedy** [comment]
Hey @devksingh4, thanks for reporting this. We are iterating on getting an initial release of the new charms and snap out the door. Currently, we have things in different states in different places and won't be creating official releases for another week or so. We will have documentation coming out that will detail how to get things up and running using the snap.snap or the slurm.tar.gz  - over the next week or so  as we create the initial release of this stack. I'll be sure and keep you posted.

**Comment by devksingh4** [comment]
Of course, I completely understand. Just wanted to make sure that you are aware of the issue (or can mark as invalid).
